package com.sofency.community.mapper;

import com.sofency.community.pojo.ForumUsers;
import com.sofency.community.pojo.ForumUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;

@Component
public interface ForumUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forumusers
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    long countByExample(ForumUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forumusers
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    int deleteByExample(ForumUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forumusers
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forumusers
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    int insert(ForumUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forumusers
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    int insertSelective(ForumUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forumusers
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    List<ForumUsers> selectByExampleWithRowbounds(ForumUsersExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forumusers
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    List<ForumUsers> selectByExample(ForumUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forumusers
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    ForumUsers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forumusers
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    int updateByExampleSelective(@Param("record") ForumUsers record, @Param("example") ForumUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forumusers
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    int updateByExample(@Param("record") ForumUsers record, @Param("example") ForumUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forumusers
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    int updateByPrimaryKeySelective(ForumUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forumusers
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    int updateByPrimaryKey(ForumUsers record);
}