package com.sofency.community.pojo;

public class ForumUsers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forumusers.id
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forumusers.password
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forumusers.email
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forumusers.github_url
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    private String githubUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forumusers.gmt_create
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forumusers.tags
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    private String tags;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forumusers.id
     *
     * @return the value of forumusers.id
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forumusers.id
     *
     * @param id the value for forumusers.id
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forumusers.password
     *
     * @return the value of forumusers.password
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forumusers.password
     *
     * @param password the value for forumusers.password
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forumusers.email
     *
     * @return the value of forumusers.email
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forumusers.email
     *
     * @param email the value for forumusers.email
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forumusers.github_url
     *
     * @return the value of forumusers.github_url
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    public String getGithubUrl() {
        return githubUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forumusers.github_url
     *
     * @param githubUrl the value for forumusers.github_url
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    public void setGithubUrl(String githubUrl) {
        this.githubUrl = githubUrl == null ? null : githubUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forumusers.gmt_create
     *
     * @return the value of forumusers.gmt_create
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forumusers.gmt_create
     *
     * @param gmtCreate the value for forumusers.gmt_create
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forumusers.tags
     *
     * @return the value of forumusers.tags
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forumusers.tags
     *
     * @param tags the value for forumusers.tags
     *
     * @mbg.generated Mon Mar 16 23:59:06 CST 2020
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }
}