package com.sofency.community.pojo;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbg.generated Thu Sep 24 23:51:55 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content_url
     *
     * @mbg.generated Thu Sep 24 23:51:55 CST 2020
     */
    private String contentUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.img_url
     *
     * @mbg.generated Thu Sep 24 23:51:55 CST 2020
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbg.generated Thu Sep 24 23:51:55 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.date_txt
     *
     * @mbg.generated Thu Sep 24 23:51:55 CST 2020
     */
    private String dateTxt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbg.generated Thu Sep 24 23:51:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbg.generated Thu Sep 24 23:51:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content_url
     *
     * @return the value of news.content_url
     *
     * @mbg.generated Thu Sep 24 23:51:55 CST 2020
     */
    public String getContentUrl() {
        return contentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content_url
     *
     * @param contentUrl the value for news.content_url
     *
     * @mbg.generated Thu Sep 24 23:51:55 CST 2020
     */
    public void setContentUrl(String contentUrl) {
        this.contentUrl = contentUrl == null ? null : contentUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.img_url
     *
     * @return the value of news.img_url
     *
     * @mbg.generated Thu Sep 24 23:51:55 CST 2020
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.img_url
     *
     * @param imgUrl the value for news.img_url
     *
     * @mbg.generated Thu Sep 24 23:51:55 CST 2020
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbg.generated Thu Sep 24 23:51:55 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbg.generated Thu Sep 24 23:51:55 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.date_txt
     *
     * @return the value of news.date_txt
     *
     * @mbg.generated Thu Sep 24 23:51:55 CST 2020
     */
    public String getDateTxt() {
        return dateTxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.date_txt
     *
     * @param dateTxt the value for news.date_txt
     *
     * @mbg.generated Thu Sep 24 23:51:55 CST 2020
     */
    public void setDateTxt(String dateTxt) {
        this.dateTxt = dateTxt == null ? null : dateTxt.trim();
    }
}