package com.sofency.community.pojo;

public class Notify {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.id
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.receiver
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    private Long receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.sender
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    private Long sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.status
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.type
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.gmt_create
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.parent_id
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    private Long parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.id
     *
     * @return the value of notify.id
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.id
     *
     * @param id the value for notify.id
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.receiver
     *
     * @return the value of notify.receiver
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.receiver
     *
     * @param receiver the value for notify.receiver
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.sender
     *
     * @return the value of notify.sender
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    public Long getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.sender
     *
     * @param sender the value for notify.sender
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    public void setSender(Long sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.status
     *
     * @return the value of notify.status
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.status
     *
     * @param status the value for notify.status
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.type
     *
     * @return the value of notify.type
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.type
     *
     * @param type the value for notify.type
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.gmt_create
     *
     * @return the value of notify.gmt_create
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.gmt_create
     *
     * @param gmtCreate the value for notify.gmt_create
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.parent_id
     *
     * @return the value of notify.parent_id
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.parent_id
     *
     * @param parentId the value for notify.parent_id
     *
     * @mbg.generated Tue Mar 03 23:11:17 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
}